application: your-application-id
version: master
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: on

automatic_scaling:
  max_idle_instances: 2
  min_pending_latency: 15.0s

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed.png

- url: /css
  mime_type: text/css
  static_dir: static/css

- url: /js
  mime_type: text/javascript
  static_dir: static/js

- url: /img/(.*\.(gif|png|jpg|jpeg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg|jpeg))

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.2.3"
